# Generated by Django 3.2.8 on 2021-10-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='florNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flor_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'florNumber',
            },
        ),
        migrations.AlterField(
            model_name='barcodes',
            name='flor_num',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='api.flornumber'),
        ),
    ]
