# Generated by Django 3.2.8 on 2021-10-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211016_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodes',
            name='flor_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flornumber'),
        ),
        migrations.AlterField(
            model_name='flornumber',
            name='flor_number',
            field=models.FloatField(),
        ),
    ]
