# Generated by Django 3.2.8 on 2021-10-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211017_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flornumber',
            name='flor_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='flornumber',
            table=None,
        ),
    ]
