# Generated by Django 3.2.8 on 2021-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211017_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodes',
            name='flor_num',
            field=models.CharField(max_length=100),
        ),
    ]
