# Generated by Django 3.2.8 on 2021-10-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_barcodes_flor_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodes',
            name='flor_num',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='api.flornumber'),
        ),
        migrations.AlterModelTable(
            name='flornumber',
            table='florNumber',
        ),
    ]
