# Generated by Django 3.2.8 on 2021-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_barcodes_flor_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodes',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
