# Generated by Django 3.2.8 on 2021-10-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_barcodes_update'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barcodes',
            table=None,
        ),
    ]
