# Generated by Django 3.2.8 on 2021-10-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_barcodes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barcodes',
            table='barcodes',
        ),
    ]
