# Generated by Django 3.2.8 on 2021-11-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_barcodes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('type_sequence', models.CharField(max_length=100)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flor_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flornumber')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
