# Generated by Django 3.2.8 on 2021-11-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211110_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='type_sequence',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='flor_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flornumber'),
        ),
    ]
