# Generated by Django 3.2.8 on 2021-11-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_typesequence'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typesequence',
            table='TypeSequence',
        ),
    ]
