# Generated by Django 3.2.11 on 2022-01-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_typesequence_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactionsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('type_sequence', models.CharField(blank=True, max_length=100, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flor_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flornumber')),
            ],
            options={
                'db_table': 'transactions_db',
            },
        ),
    ]
